image: ruby

stages:
  - test

before_script:
  - gem update bundler
  - bundle install

ruby2.3:
  image: ruby:2.3
  script: bundle exec rspec

ruby2.4:
  image: ruby:2.4
  script: bundle exec rspec

ruby2.5:
  image: ruby:2.5
  script: bundle exec rspec

ruby2.6:
  image: ruby:2.6
  script: bundle exec rspec

ruby2.7:
  image: ruby:2.7
  script: bundle exec rspec

jruby:
  image: jruby
  script: bundle exec jruby --debug -S rspec

