image: ruby

stages:
  - test

before_script:
  - bundle install

script:
  - rspec

ruby2.3:
  image: ruby:2.3

ruby2.4:
  image: ruby:2.4

ruby2.5:
  image: ruby:2.5

ruby2.6-rc:
  image: ruby:2.6-rc
